services:
  # service name: db
  db:
    image: postgres:16
    # these env variables are read by the postgres image on first startup to initialize the database.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432" # left side is your machine's port, right side is container port.
    # this is where postgres will store its data.
    volumes:
      - dbdata:/var/lib/postgresql/data
    # healthcheck is Compose asking: Are you ready?
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"] # pg_isready checks if the DB is ready to accept connections.
      interval: 2s # check every 2 seconds.
      timeout: 3s # each check can take up to 3 seconds.
      retries: 30 # try 30 times before giving up.

  # this is a one time job container that runs the migrations.
  migrate:
    image: migrate/migrate:latest # popular migration CLI
    volumes:
      - ./services/orders/migrations:/migrations # mounts your local migrations folder to the container.
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/orders?sslmode=disable",
        "up",
      ]
    depends_on:
      db:
        condition: service_healthy # this makes sure the db is ready before running the migrations.

  orders:
    # compose will run docker build using Dockerfile in ./services/orders directory. It creates an image for your Go service.
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/orders?sslmode=disable"
      INVENTORY_GRPC_ADDR: "inventory:9090"
      KAFKA_BROKERS: "redpanda:9092"
    ports:
      - "8080:8080"
    #  compose will start db container before orders container starts.
    depends_on:
      migrate:
        condition: service_completed_successfully # this makes sure the migrations are completed successfully before starting the orders container.
      inventory:
        condition: service_started # this makes sure the inventory container is started before the orders container starts.
  inventory:
    build:
      context: .
      dockerfile: services/inventory/Dockerfile
    environment:
      KAFKA_BROKERS: "redpanda:9092"
    ports:
      - "9090:9090"

  # Redpanda is like Kafka: a server that lets services publish events and other services consume events.
  redpanda:
    image: redpandadata/redpanda:latest
    # this is the command run inside the container.
    command:
      - redpanda
      - start
      - --overprovisioned # optimize redpanda in a small dev container
      - --smp
      - "1" # use 1 CPU core
      - --memory
      - 1G # give redpanda upto 1GB of memory
      - --reserve-memory
      - 0M # reserve 0MB for internal use
      - --node-id
      - "0" # this node ID is 0
      - --check=false # skips some startup checks helps in Docker/dev environment.
      # this tells redpanda to listen on both internal and external endpoints.
      - --kafka-addr
      # internal://0.0.0.0:9092 -> used by other containers in the same Docker network. port 9092 is the default Kafka port.
      # external://0.0.0.0:19092 -> used by your laptop (host machine). mapped to host port 19092 via ports.
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      # this is the address redpanda tells clients to use.
      # we are telling here internal clients should use redpanda:9092
      # and external clients should use localhost:19092
      - internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092" # exposes Kafka externally so your laptop tools can connect to localhost:19092.
      - "9644:9644" # exposes Redpanda's admin/metrics API

volumes:
  # define a volume called dbdata. without this, data would be lost when the container is stopped.
  dbdata:

# docker compose up --build -> before starting the container, (re)build the image that come from "build:" section.
# docker comppose up -> will usually reuse the last build image if it exists. And if you have any changes in the code you might not see them as you updated the code.
